[workspace]
resolver = "3"
members = ["pacstall","pacstall-builder","pacstall-core"]


[workspace.package]
authors = ["Elsie19 <hwengerstickel@protonmail.com>","D-Brox <davidfbg00@gmail.com>"]
edition = "2024"
version = "0.1.0"
